import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tennis Store - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto md:mb-5 md:mt-10 px-4 md:px-0">
        <div>Data mocked with MSW.js</div>
      </section>

      <footer></footer>
    </div>
  );
};

export default Home;
