import { NextPage } from "next";
import Head from "next/head";
import { Bag } from "../../mocks/data/bags";
import Image from "next/image";
import { Params } from "next/dist/next-server/server/router";

interface BagPage {
  bag: Bag;
}

const BagPage: NextPage<BagPage> = ({ bag }) => {
  return (
    <div>
      <Head>
        <title>Tennis Store - {bag.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto md:mb-5 md:mt-10 px-4 md:px-0">
        <section className="flex gap-4 px-10">
          <ul className="flex flex-col">
            {bag.images.map((image) => (
              <li key={image.slice(23, image.length - 4)} className="pb-2 pt-2">
                <Image
                  src={image}
                  alt={image.slice(23, image.length - 4)}
                  width="70"
                  height="70"
                  className="mx-auto relative z-1"
                />
              </li>
            ))}
          </ul>
          <Image
            src={bag.images[0]}
            alt={bag.name}
            width="640"
            height="640"
            className="mx-auto relative z-1"
          />
          <div className="flex flex-col px-4">
            <h1 className="font-sans font-bold text-2xl mb-10">{bag.name}</h1>
            <ul className="flex flex-wrap items-center mb-10">
              <p className="font-bold text-sm mr-4">Colors</p>
              {bag.colors.map((color) => (
                <li className="text-xs">{color}</li>
              ))}
            </ul>
            <button className="pt-4 pb-4 pl-8 pr-8 text-base font-bold text-white bg-slate-600">
              Add To Cart
            </button>
          </div>
        </section>
        <section className="flex flex-col bg-gray-50 px-10 pt-10 pb-10">
          <h2 className="mb-10 text-xl font-bold">Description</h2>
          <p className="font-medium leading-relaxed font-sans text-lg">
            {bag.description}
          </p>
        </section>
        <section className="flex flex-col bg-slate-600 px-10 pt-10 pb-10">
          <h2 className="mb-10 text-xl font-bold text-white">
            Technical Characteristics
          </h2>
          <ul className="grid grid-cols-2 text-white gap-4">
            <li>
              <span className="font-bold mr-2">Racket Capacity:</span>
              <span>{bag.technicalCharacteristics.racketCapacity}</span>
            </li>
            <li>
              <span className="font-bold mr-2">Dimensions:</span>
              <span>{bag.technicalCharacteristics.dimensions}</span>
            </li>
            <li>
              <span className="font-bold mr-2">
                Number of Insulated Compartments:
              </span>
              <span>
                {bag.technicalCharacteristics.numberOfInsulatedCompartments}
              </span>
            </li>
            <li>
              <span className="font-bold mr-2">Number of Handles:</span>
              <span>{bag.technicalCharacteristics.numberOfHandles}</span>
            </li>
            <li className="flex">
              <span className="font-bold mr-2">Number of Pockets:</span>
              <div className="flex flex-col">
                {bag.technicalCharacteristics.numberOfPockets.map((value) => (
                  <span key={value}>{value}</span>
                ))}
              </div>
            </li>
            <li>
              <span className="font-bold mr-2">Number of Straps:</span>
              <span>{bag.technicalCharacteristics.numberOfStraps}</span>
            </li>
            <li className="flex">
              <span className="font-bold mr-2">Composition:</span>
              <div className="flex flex-col">
                {bag.technicalCharacteristics.composition.map((value) => (
                  <span key={value}>{value}</span>
                ))}
              </div>
            </li>
            <li>
              <span className="font-bold mr-2">Capacity:</span>
              <span>{bag.technicalCharacteristics.capacity}</span>
            </li>
          </ul>
        </section>
      </section>
    </div>
  );
};

export async function getStaticPaths() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_MOOCKING_URL}/bags`);
  const bags: Bag[] = await res.json();

  const paths = bags.map((bag: Bag) => ({
    params: { id: bag.id },
  }));

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }: Params) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_MOOCKING_URL}/bags/${params.id}`
  );
  const bag: Bag = await res.json();

  return {
    props: {
      bag,
    },
  };
}

export default BagPage;
